#!/usr/bin/env python3
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT_PATH = REPO_ROOT / "snapshots" / "v0.4.0.json"
LIB_RS = REPO_ROOT / "rust" / "fips-proto-defs" / "src" / "lib.rs"

_ENUM_TABLES = [("LinkMessageType", "LINK_MSG"), ("DisconnectReason", "DISC_REASON")]


def render(snap):
    up = snap["upstream"]
    lines = [
        "#![no_std]",
        "// AUTO-GENERATED by tools/render_crate.py. DO NOT EDIT.",
        "// Source: canonical %s@%s" % (up["authority"], up["ref"]),
        "// Commit: %s" % up["commit"],
        "",
    ]
    for name in sorted(snap.get("consts", {})):
        c = snap["consts"][name]
        lines.append("pub const {}: {} = {};".format(name, c["type"], c["value"]))
    for enum_name, prefix in _ENUM_TABLES:
        variants = snap.get("enums", {}).get(enum_name, {})
        if not variants:
            continue
        lines.append("pub const {}: &[(u8, &str)] = &[".format(prefix))
        for vname in sorted(variants, key=lambda k: variants[k]):
            lines.append('    (0x{:02X}, "{}"),'.format(variants[vname], vname))
        lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main(argv=None):
    snap = json.loads(SNAPSHOT_PATH.read_text(encoding="utf-8"))
    LIB_RS.parent.mkdir(parents=True, exist_ok=True)
    LIB_RS.write_text(render(snap), encoding="utf-8")
    sys.stdout.write("wrote %s\n" % LIB_RS.relative_to(REPO_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
